record:
  repo_id: &repo_id "zgca/pour_water" # huggingface repo: <hf_username>/<dataset_repo_id>
  fps: 30 # dataset and camera frame rate

  robot:
    ip: &ip "192.168.119.3" # robot ip
    enable_gripper: &enable_gripper True
    gripper_init_open: &gripper_init_open False # 初始化到初始位姿后，夹爪是否保持打开
    gripper: &gripper
      choice: robotiq # one of: robotiq, dh, qb
      qb:
        port: "/dev/ttyUSB0"
        device_id: 1
        open: [0, 0]
        close: [10000, 0]
      dh:
        port: "/dev/ttyUSB0"
        force: 100
        open: 1000
        close: 0
      robotiq:
        ip: *ip
        port: 63352
        speed: 255
        force: 255
        open: 0
        close: 255
    servo_speed: 0.1
    servo_accel: 0.1
    servo_lookahead_time: 0.1
    servo_gain: 500

  teleop:
    port: "/dev/ttyACM0" # master-arm serial port
    joint_coef: [1.0, -1.0, -1.0, -1.0, -1.0, -1.0]
    resync_key: "s"
    resync_settle_seconds: 0.2
    gripper_trigger_threshold: 400.0
    use_gripper: True

  task:
    description: "Pick up the measuring cylinder and pour an appropriate amount of water into the beaker." # task description
    num_episodes: 100 # number of episodes to record
    display: True # whether to display the data during recording
    resume: False
    teleop_init_joint: [-1.6285174528705042, -1.6196133098998011, 2.112854782735006, -0.43745441854510503, 1.5982029438018799, 0]
    keyboard_init_joint: [-1.6285174528705042, -1.6196133098998011, 2.112854782735006, -0.43745441854510503, 1.5982029438018799, 0]
    close_gripper_before_recording: False # True 时在正式录制前执行一次不写入数据集的闭夹爪动作

  time:
    episode_time_sec: 3000 # max time per episode in seconds
    reset_time_sec: 60 # max time to reset between episodes in seconds
    save_meta_period: 1 # save metadata after every N episodes

  cameras:
    enable: True # false 时不打开 OpenCV 相机，改为使用 mock 图像
    storage_width: 640  # 存储图像宽度 (480p: 854x480)
    storage_height: 360  # 存储图像高度
    wrist:
      source: "2" # OpenCV source: camera index, /dev/video path, or network stream URL
      width: 1280
      height: 720
      rotation: 0
    exterior:
      source: "0" # OpenCV source: camera index, /dev/video path, or network stream URL
      width: 1280
      height: 720
      rotation: 0

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  repo_id: *repo_id
  episode_idx: 0 # episode index to replay
  robot:
    ip: *ip
    enable_gripper: *enable_gripper
    gripper_init_open: *gripper_init_open
    gripper: *gripper

visualize:
  repo_id: *repo_id
  episode_index: 0 # episode index to visualize
