#!/usr/bin/env bash
set -euo pipefail

# map_device.sh
# 用法: ./map_device.sh /dev/ttyUSB0 left_gripper
# 手动为单个设备生成映射文件，保存在 ./mappings/<logical>.map

MAPPINGS_DIR="./mappings"

usage() {
  echo "用法: $0 <device-node> <logical-name>"
  echo "例如: $0 /dev/ttyUSB0 left_gripper"
  exit 2
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "需要命令: $1" >&2; exit 1; }
}

require_cmd udevadm
require_cmd readlink

[ "$#" -eq 2 ] || usage
DEVNODE="$1"
LOGICAL="$2"

if [ ! -e "$DEVNODE" ]; then
  echo "设备节点不存在: $DEVNODE" >&2
  exit 1
fi

mkdir -p "$MAPPINGS_DIR"

props=$(udevadm info --query=property --name="$DEVNODE" 2>/dev/null || true)

if [ -z "$props" ]; then
  echo "无法读取 udev 属性，确保设备存在并且 udevadm 可用" >&2
  exit 1
fi

type="unknown"
if printf "%s" "$props" | grep -q '^SUBSYSTEM=tty'; then
  type="tty"
elif printf "%s" "$props" | grep -q '^SUBSYSTEM=video4linux'; then
  type="video"
fi

id_serial_short=$(printf "%s" "$props" | awk -F= '/^ID_SERIAL_SHORT=/{print $2; exit}')
id_serial=$(printf "%s" "$props" | awk -F= '/^ID_SERIAL=/{print $2; exit}')
vendor=$(printf "%s" "$props" | awk -F= '/^ID_VENDOR_ID=/{print $2; exit}')
model=$(printf "%s" "$props" | awk -F= '/^ID_MODEL_ID=/{print $2; exit}')
kernel=$(printf "%s" "$props" | awk -F= '/^DEVNAME=/{print $2; exit}')

outfile="$MAPPINGS_DIR/${LOGICAL}.map"

cat >"$outfile" <<EOF
# Mapping generated by map_device.sh on $(date)
LOGICAL=${LOGICAL}
DEVNODE=${DEVNODE}
TYPE=${type}
ID_SERIAL_SHORT=${id_serial_short}
ID_SERIAL=${id_serial}
ID_VENDOR_ID=${vendor}
ID_MODEL_ID=${model}
DEVNAME=${kernel}
EOF

echo "已保存映射: $outfile"
echo "内容:"
sed -n '1,200p' "$outfile"

echo
echo "提示: 请把所有映射文件保存在项目目录的 mappings/ 下。"

exit 0
